#!/bin/bash

set -xe

pwd
env

cf api $PWS_API

cf login -u $PWS_USER -p $PWS_PWD -o $PWS_ORG -s $PWS_SPACE

cf apps

set +e
cf apps | grep "main-$PWS_APP_SUFFIX" | grep green
if [ $? -eq 0 ]
then
  echo "green" > ./current-app-info/current-app.txt
  echo "blue" > ./current-app-info/next-app.txt
else
  echo "blue" > ./current-app-info/current-app.txt
  echo "green" > ./current-app-info/next-app.txt
fi
set -xe
