#!/bin/bash

set -xe

pwd
env

cf api $PWS_API

cf login -u $PWS_USER -p $PWS_PWD -o $PWS_ORG -s $PWS_SPACE

cf apps

cf routes

export PWS_DOMAIN_NAME=cfapps.io
export MAIN_ROUTE_HOSTNAME=main-app-hello

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_HOSTNAME=$NEXT_APP_COLOR-app-hello

export CURRENT_APP_COLOR=$(cat ./current-app-info/current-app.txt)
export CURRENT_APP_HOSTNAME=$CURRENT_APP_COLOR-app-hello

cf map-route $NEXT_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME

set +e
cf unmap-route $CURRENT_APP_HOSTNAME $PWS_DOMAIN_NAME --hostname $MAIN_ROUTE_HOSTNAME
set -e

cf routes
