groups: []
resources:
- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.23.0
- name: pcf-ops-manager
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/rootfs
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
    - get: pivnet-opsman-product
      resource: pcf-ops-manager
      params:
        globs:
        - '*.ova'
  - task: deploy
    file: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task.yml
    params:
      GOVC_CA_CERT: {{vcenter_ca_cert}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_HOST: {{om_vm_host}}
      GOVC_INSECURE: {{vcenter_insecure}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_IP: {{om_ip}}
      OM_NETMASK: {{om_netmask}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OM_VM_FOLDER: {{om_vm_folder}}
      OM_VM_NAME: {{om_vm_name}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}
      OPS_MGR_SSH_PWD: {{opsman_ssh_password}}
      OPSMAN_DISK_TYPE: {{opsman_disk_type}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
- name: configure-director
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/rootfs
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
    - get: pcf-ops-manager
      passed:
      - deploy-opsman
      trigger: true
      params:
        globs: []
  - task: config-opsman-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
  - task: configure-director
    file: pcf-pipelines/install-pcf/vsphere/tasks/config-opsdir/task.yml
    params:
      AZ_1: {{az_1_name}}
      AZ_1_CLUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      AZ_2: {{az_2_name}}
      AZ_2_CLUSTER_NAME: {{az_2_cluster_name}}
      AZ_2_RP_NAME: {{az_2_rp_name}}
      AZ_3: {{az_3_name}}
      AZ_3_CLUSTER_NAME: {{az_3_cluster_name}}
      AZ_3_RP_NAME: {{az_3_rp_name}}
      BOSH_DISK_PATH: {{bosh_disk_path}}
      BOSH_TEMPLATE_FOLDER: {{bosh_template_folder}}
      BOSH_VM_FOLDER: {{bosh_vm_folder}}
      DEPLOYMENT_EXCLUDED_RANGE: {{deployment_excluded_range}}
      DEPLOYMENT_NETWORK_NAME: {{deployment_network_name}}
      DEPLOYMENT_NW_AZS: {{deployment_nw_azs}}
      DEPLOYMENT_NW_CIDR: {{deployment_nw_cidr}}
      DEPLOYMENT_NW_DNS: {{deployment_nw_dns}}
      DEPLOYMENT_NW_GATEWAY: {{deployment_nw_gateway}}
      DEPLOYMENT_VCENTER_NETWORK: {{deployment_vsphere_network}}
      DYNAMIC_SERVICES_EXCLUDED_RANGE: {{dynamic_services_excluded_range}}
      DYNAMIC_SERVICES_NETWORK_NAME: {{dynamic_services_network_name}}
      DYNAMIC_SERVICES_NW_AZS: {{dynamic_services_nw_azs}}
      DYNAMIC_SERVICES_NW_CIDR: {{dynamic_services_nw_cidr}}
      DYNAMIC_SERVICES_NW_DNS: {{dynamic_services_nw_dns}}
      DYNAMIC_SERVICES_NW_GATEWAY: {{dynamic_services_nw_gateway}}
      DYNAMIC_SERVICES_VCENTER_NETWORK: {{dynamic_services_vsphere_network}}
      ENABLE_VM_RESURRECTOR: {{enable_vm_resurrector}}
      EPHEMERAL_STORAGE_NAMES: {{ephemeral_storage_names}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      INFRA_EXCLUDED_RANGE: {{infra_excluded_range}}
      INFRA_NETWORK_NAME: {{infra_network_name}}
      INFRA_NW_AZS: {{infra_nw_azs}}
      INFRA_NW_CIDR: {{infra_nw_cidr}}
      INFRA_NW_DNS: {{infra_nw_dns}}
      INFRA_NW_GATEWAY: {{infra_nw_gateway}}
      INFRA_VCENTER_NETWORK: {{infra_vsphere_network}}
      IS_SERVICE_NETWORK: {{is_service_network}}
      MAX_THREADS: {{max_threads}}
      NSX_ADDRESS: {{nsx_address}}
      NSX_CA_CERTIFICATE: {{nsx_ca_certificate}}
      NSX_NETWORKING_ENABLED: {{nsx_networking_enabled}}
      NSX_PASSWORD: {{nsx_password}}
      NSX_USERNAME: {{nsx_username}}
      NTP_SERVERS: {{ntp_servers}}
      OPS_DIR_HOSTNAME: {{ops_dir_hostname}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PERSISTENT_STORAGE_NAMES: {{persistent_storage_names}}
      SERVICES_EXCLUDED_RANGE: {{services_excluded_range}}
      SERVICES_NETWORK_NAME: {{services_network_name}}
      SERVICES_NW_AZS: {{services_nw_azs}}
      SERVICES_NW_CIDR: {{services_nw_cidr}}
      SERVICES_NW_DNS: {{services_nw_dns}}
      SERVICES_NW_GATEWAY: {{services_nw_gateway}}
      SERVICES_VCENTER_NETWORK: {{services_vsphere_network}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      VCENTER_DATA_CENTER: {{vcenter_datacenter}}
      VCENTER_DISK_TYPE: {{vm_disk_type}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_USR: {{vcenter_usr}}
- name: deploy-director
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/rootfs
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
    - get: pcf-ops-manager
      passed:
      - configure-director
      trigger: true
      params:
        globs: []
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}

- name: wipe-env
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/rootfs
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
  - task: wipe
    file: pcf-pipelines/install-pcf/vsphere/tasks/wipe-env/task.yml
    params:
      GOVC_CA_CERT: {{vcenter_ca_cert}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_HOST: {{om_vm_host}}
      GOVC_INSECURE: {{vcenter_insecure}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_IP: {{om_ip}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
