---
resources:
- name: trigger-every-3-minutes
  type: time
  source:
    interval: 3m

jobs:
- name: Run-Forrest-Run
  plan:
  - get: trigger-every-3-minutes
    trigger: true
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered every 3 minutes."
          sleep 10   # so you can see the running job effect in the UI

- name: Run-Bubba-Run
  plan:
  - get: trigger-every-3-minutes
    trigger: true
    passed:
      - Run-Forrest-Run
  - task: do-another-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of second job's task."
          sleep 10   # so you can see the running job effect in the UI
