groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - load-tests
  - promote-new-version

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/lsilvapvt/concourse-pipeline-samples.git
- name: pws
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: false
    space: {{pws-space}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: prepare-app-manifest
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/app-manifest-prep.yml
  - put: pws
    params:
      manifest: app-manifest-output/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app

- name: load-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    passed:
      - deploy-app
  - task: get-current-app-color
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: run-load-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/load-tests.yml

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    passed:
      - load-tests
  - task: get-current-app-color
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: switch-app-routes
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/update-routes.yml
    params:
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
